[package]
name = "boltzman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.20.2"
rand="0.8.5"
text_io = "0.1.12"
